image: docker.vokal.io/node-testing
env:
script:
    - npm install
    - bower --allow-root install
    - npm install -g grunt
    - npm test
notify:
    email:
        recipients:
            - chris@nelsoncash.com # swap this for the project
