image: bradrydzewski/node:0.10
script:
    - echo this is working
    - npm install
    - bower --allow-root install
    - npm install -g grunt
    - npm test
notify:
    email:
        recipients:
            - chris@nelsoncash.com # swap this for the project
