image: bradrydzewski/node:0.10
script:
    - npm install
    - npm install -g bower
    - bower --allow-root install
    - chmod +x run-build.sh
    - ./run-build.sh
notify:
    email:
        recipients:
            - chris@nelsoncash.com # swap this for the project